name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:  

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5

      - name: Setup Protobuf
        uses: ./.github/actions/setup-protobuf

      - name: Generate protobuf files
        run: go generate ./sinks/pb/

      - name: GolangCI-Lint 
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  Unit-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: 'go.sum'

    - name: Setup Protobuf
      uses: ./.github/actions/setup-protobuf

    - name: Test
      run: |
        go generate ./sinks/pb
        go test -timeout 10m -failfast -v -coverprofile=profile.cov ./...

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: profile.cov 
