# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:  

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5

      - name: GolangCI-Lint 
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: 'go.sum'

    - name: Test
      run: |
        go test -timeout 20m -failfast -v -coverprofile=profile.cov ./...

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: profile.cov 
